### PR TITLE
Fix BookmarksComboBoxWidget not expanding

### LINKED ISSUE #1615: When adding folder in add bookmark dialog, treeview does not expand properly
Steps to reproduce:
1. Go to Manage Bookmarks
2. Right-click any folder
3. Select Add Bookmark > Add Folder
4. Click on new and enter a new folder name
5. Click on new again and enter a new folder name
6. Expand 'Folder' tree view

Results:
Tree view does not show the last created folder.

Expected:
Tree view should be fully expanded.

Video demo:
https://youtu.be/ftzCjFFsIuk

### PR DESCRIPTION
**Pull request by fnkkio**
Fixes #1615 

Video demo:
https://youtu.be/SUB8_IkVpv8

### CODE REVIEW

File: src/ui/BookmarksComboBoxWidget.cpp [hunk 1]
```diff
@@ -41,6 +41,7 @@ BookmarksComboBoxWidget::BookmarksComboBoxWidget(QWidget *parent) : ComboBoxWidg
 void BookmarksComboBoxWidget::createFolder()
 {
 	const QString title(QInputDialog::getText(this, tr("Folder Name"), tr("Select name of new folder:")));
+	BookmarksModel::Bookmark *prevFolder = getCurrentFolder();
```
Comment (Emdek) [inline src/ui/BookmarksComboBoxWidget.cpp]: We avoid this kind of initialization syntax, it should be:
```
BookmarksModel::Bookmark *previousFolder(getCurrentFolder());
```
And I think that it could be fixed in `BookmarksComboBoxWidget::setCurrentFolder()` instead, without adding condition (always expand).

**Comment by fnkkio** [comment]
@Emdek Updated according to your remarks.

File: src/ui/BookmarksComboBoxWidget.cpp [hunk 2]
```diff
@@ -97,6 +97,7 @@ void BookmarksComboBoxWidget::setCurrentFolder(BookmarksModel::Bookmark *folder)
 	if (folder)
 	{
 		setCurrentIndex(folder->index());
+		getView()->expand(folder->index());
```
Comment (Emdek) [inline src/ui/BookmarksComboBoxWidget.cpp]: Just a minor detail, usually we put empty newlines between groups of calls dealing with different objects.
Also, I'm not 100% sure,but  I kind of expected that it would be needed to call it on parent index instead, does it still work properly?

Comment (fnkkio) [reply src/ui/BookmarksComboBoxWidget.cpp]: @Emdek still works properly calling it on child.

**Comment by fnkkio** [comment]
@Emdek Added missing newline.

File: src/ui/BookmarksComboBoxWidget.cpp (hunk 2 above)
Comment (Emdek) [reply src/ui/BookmarksComboBoxWidget.cpp]: @fnkkio, OK.
